package Enums;

public enum SignalEnum {
    GOODBYE,
    INCORRECT_INPUT,
    INCORRECT_INPUT_BOOLEAN,
    INCORRECT_INPUT_YEAR,
    INCORRECT_INPUT_STRENGTH,
    NOT_AN_OPTION,
    CHOOSE_HERO,
    CHOOSE_EDIT_OPTION,
    CHOOSE_SEARCH_OPTION,
    HERO_FOUND,
    HEROES_FOUND,
    NO_HEROES_FOUND,
    ASK_FOR_EDIT,
    INCORRECT_INPUT_INT,
    ASK_FOR_NAME,
    ASK_IF_SUPERHERONAME,
    ASK_FOR_SUPERHERONAME,
    ASK_IF_HUMAN,
    ASK_FOR_POWERS,
    ASK_FOR_CREATION_YEAR,
    ASK_FOR_STRENGTH_LEVEL
}
